## 협업 필터링

In [5]:
import numpy as np

user1 = np.array([0,1,2,3,4,5])
user2 = np.array([0,1,4,6,1,4])

In [2]:
# 유클리드 거리 : 거리가 짧을수록 유사하다.
sum((user1 - user2)**2)**(1/2)

4.795831523312719

In [3]:
# 코사인 유사도
user1 = np.array([4,5,3,2,1])
user2 = np.array([3,2,4,2,2])

a=sum(user1 * user2)
b = (sum(user1 ** 2) **(1/2) * sum(user2 ** 2) **(1/2))
a/b

0.8867021970429452

In [4]:
import numpy as np

A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

np.sum(A)


49

In [5]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, np.nan, 3, 1],
    [3, 1, 4, 3, 1],
])

np.sum(A)

nan

In [6]:
np.nansum(A)

47.0

In [7]:
np.nanmean(A)

2.473684210526316

In [8]:
A = np.array([[4,1,5,np.nan,1],
     [2,3,np.nan,2,3],
     [1,np.nan,4,1,3],
     [np.nan,2,4,np.nan,2],
     [1,np.nan,4,1,3]])

A

array([[ 4.,  1.,  5., nan,  1.],
       [ 2.,  3., nan,  2.,  3.],
       [ 1., nan,  4.,  1.,  3.],
       [nan,  2.,  4., nan,  2.],
       [ 1., nan,  4.,  1.,  3.]])

In [9]:
np.nan_to_num(A, nan=0) # 누락값 0으로 채우기


array([[4., 1., 5., 0., 1.],
       [2., 3., 0., 2., 3.],
       [1., 0., 4., 1., 3.],
       [0., 2., 4., 0., 2.],
       [1., 0., 4., 1., 3.]])

In [10]:
# Mean Normalization 으로 누락값 채우기
A_copy = A.copy()

for i in range(len(A_copy)):
    mean = np.nanmean(A_copy[i])
    # print(mean)
    A_copy[i]=np.nan_to_num(A_copy[i], nan=mean)
    A_copy[i] -= mean

A_copy



array([[ 1.25      , -1.75      ,  2.25      ,  0.        , -1.75      ],
       [-0.5       ,  0.5       ,  0.        , -0.5       ,  0.5       ],
       [-1.25      ,  0.        ,  1.75      , -1.25      ,  0.75      ],
       [ 0.        , -0.66666667,  1.33333333,  0.        , -0.66666667],
       [-1.25      ,  0.        ,  1.75      , -1.25      ,  0.75      ]])

In [2]:
import pandas as pd

ratings = pd.read_csv('/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/ratings.csv')
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
df = ratings.pivot_table(index='userId', columns='movieId', values='rating',aggfunc='sum').values  # values 행렬로 바꿔줌

df

array([[4. , nan, 4. , ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [2.5, 2. , 2. , ..., nan, nan, nan],
       [3. , nan, nan, ..., nan, nan, nan],
       [5. , nan, nan, ..., nan, nan, nan]])

In [6]:
nan_mask = np.isnan(df) # 누락값 있는 곳 미리 저장
nan_mask

array([[False,  True, False, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [False, False, False, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True]])

In [7]:
df_filled = df.copy()

for i in range(len(df_filled)):
    mean = np.nanmean(df_filled[i])
    # print(mean)
    df_filled[i] = np.nan_to_num(df_filled[i], nan=mean)
    # print(df_filled[i])
    df_filled[i] -= mean

df_filled

array([[-0.36637931,  0.        , -0.36637931, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.63417569, -1.13417569, -1.13417569, ...,  0.        ,
         0.        ,  0.        ],
       [-0.27027027,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.31144393,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [15]:
from sklearn.metrics.pairwise import euclidean_distances # 유클리드 거리 계산

distance_matrix=euclidean_distances(df_filled) # 유클리드 거리계산
distance_matrix


array([[ 0.        , 12.88018162, 17.71367592, ..., 32.52330461,
        12.52374725, 33.10732342],
       [12.88018162,  0.        , 13.57431978, ..., 31.40943515,
         5.18205377, 31.11334478],
       [17.71367592, 13.57431978,  0.        , ..., 33.81269431,
        13.1676513 , 33.27108605],
       ...,
       [32.52330461, 31.40943515, 33.81269431, ...,  0.        ,
        31.07357893, 42.64413263],
       [12.52374725,  5.18205377, 13.1676513 , ..., 31.07357893,
         0.        , 31.07797619],
       [33.10732342, 31.11334478, 33.27108605, ..., 42.64413263,
        31.07797619,  0.        ]])

In [16]:
a = [1,3,4,5,2]
np.argsort(a) # 정렬된 인덱스 값을 확인

array([0, 4, 1, 2, 3])

In [17]:
# 고려할 이웃의 수
k = 5

# 각 유저별로 가장 거리가 짧았던 5명이 있는 위치
nearest_neighbors=np.argsort(distance_matrix,axis=1)[:,1:k+1]  # 정렬된 인덱스 값을 확인 , 자기 자신 제외 조회
nearest_neighbors

array([[ 52,  48, 188, 213, 514],
       [ 52, 188,  48, 514,  24],
       [ 52,  48, 514, 188,  24],
       ...,
       [315, 430, 539,  71,  53],
       [ 52,  48,  53, 514, 188],
       [462, 361, 347, 292, 121]])

In [18]:
# 0 번째 사람의 영화를 추천할 예정
user = 0
user_ratings=df[user]
user_nan_mask = nan_mask[user]

# 유저가 평가하지 않은 영화의 위치
unrated_indices=np.where(user_nan_mask)[0]

# 영화별 예측된 평점들을 저장해놓을 장소
predictions = {}

neibors_indices = nearest_neighbors[user] # 이웃유저들의 평점 확인
#print(neibors_indices)


# 평가하지 않은 영화에 대해 이웃의 평점 가져오기
for movie_idx in unrated_indices:
    neigbor_ratings = [] # 이웃들이 이 영화를 몇점으로 평가했는가
    for neigbor_idx in neibors_indices:
        if not (nan_mask[neigbor_idx][movie_idx]):  # 영화를 봤는지 안봤는지
            neigbor_ratings.append(df[neigbor_idx][movie_idx])
    if neigbor_ratings !=[]:
        predictions[movie_idx] = np.mean(neigbor_ratings)

predictions

{16: 3.0,
 24: 2.0,
 55: 3.0,
 59: 3.0,
 75: 3.0,
 92: 3.0,
 116: 2.0,
 171: 5.0,
 213: 5.0,
 277: 4.333333333333333,
 338: 5.0,
 357: 5.0,
 419: 5.0,
 533: 3.0,
 584: 3.0,
 598: 3.0,
 601: 5.0,
 622: 2.0,
 630: 3.0,
 668: 5.0,
 698: 5.0,
 704: 5.0,
 809: 4.0,
 837: 5.0,
 853: 5.0,
 901: 4.5,
 1043: 3.0,
 1048: 3.0,
 1084: 3.0,
 1107: 5.0,
 1458: 5.0,
 2014: 5.0,
 2077: 4.0,
 2340: 5.0,
 2999: 5.0,
 3002: 4.5,
 3633: 4.0,
 3740: 4.0,
 4131: 4.0,
 4354: 4.0,
 4791: 4.0,
 5901: 4.25,
 6241: 4.5,
 6298: 4.5,
 6314: 5.0,
 6517: 4.5,
 6693: 5.0,
 6726: 5.0,
 6755: 5.0,
 7022: 4.5,
 7073: 4.0,
 7285: 4.0,
 7354: 4.0,
 7355: 4.666666666666667,
 7750: 4.25,
 8182: 4.0,
 8358: 4.5,
 8448: 5.0,
 8551: 5.0,
 8676: 5.0,
 8677: 5.0,
 8678: 4.0,
 8972: 4.5,
 9444: 4.5,
 9445: 4.75,
 9553: 4.0,
 9574: 4.0,
 9586: 5.0,
 9627: 4.0}

In [19]:
movies = pd.read_csv('/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/movies.csv')

movie_names = {}
for i in range(len(movies)):
    a = movies.iloc[i]
    movie_names[a['movieId']] = a['title']
movie_names

{1: 'Toy Story (1995)',
 2: 'Jumanji (1995)',
 3: 'Grumpier Old Men (1995)',
 4: 'Waiting to Exhale (1995)',
 5: 'Father of the Bride Part II (1995)',
 6: 'Heat (1995)',
 7: 'Sabrina (1995)',
 8: 'Tom and Huck (1995)',
 9: 'Sudden Death (1995)',
 10: 'GoldenEye (1995)',
 11: 'American President, The (1995)',
 12: 'Dracula: Dead and Loving It (1995)',
 13: 'Balto (1995)',
 14: 'Nixon (1995)',
 15: 'Cutthroat Island (1995)',
 16: 'Casino (1995)',
 17: 'Sense and Sensibility (1995)',
 18: 'Four Rooms (1995)',
 19: 'Ace Ventura: When Nature Calls (1995)',
 20: 'Money Train (1995)',
 21: 'Get Shorty (1995)',
 22: 'Copycat (1995)',
 23: 'Assassins (1995)',
 24: 'Powder (1995)',
 25: 'Leaving Las Vegas (1995)',
 26: 'Othello (1995)',
 27: 'Now and Then (1995)',
 28: 'Persuasion (1995)',
 29: 'City of Lost Children, The (Cité des enfants perdus, La) (1995)',
 30: 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 31: 'Dangerous Minds (1995)',
 32: 'Twelve Monkeys (a.k.a. 12 Monkeys) (199

In [20]:
# 예측된 평점을 내림차순으로 정렬
sorted_predictions = sorted(predictions.items(), key=lambda x: x[1], reverse=True)
# 추천할 영화의 수
top_N = 5
recommendations = sorted_predictions[:top_N]
df = ratings.pivot_table(index = "userId", columns = "movieId", values = "rating", aggfunc="sum")
for i in recommendations:
    movie_id = df.iloc[:, i[0]].name
    name = movie_names[movie_id]
    print(f"추천영화 : {name} (예측평점 {i[1]}점)")

추천영화 : To Wong Foo, Thanks for Everything! Julie Newmar (1995) (예측평점 5.0점)
추천영화 : Immortal Beloved (1994) (예측평점 5.0점)
추천영화 : When a Man Loves a Woman (1994) (예측평점 5.0점)
추천영화 : Airheads (1994) (예측평점 5.0점)
추천영화 : Kalifornia (1993) (예측평점 5.0점)


### 협업 필터링 추천시스템 과제

In [8]:
from sklearn.metrics.pairwise import cosine_similarity # 코사인 유사도

distance_matrix=cosine_similarity(df_filled) # 코사인 유사도
distance_matrix


array([[ 1.00000000e+00,  1.26451574e-03,  5.52577176e-04, ...,
         7.52238457e-02, -2.57125541e-02,  1.09323166e-02],
       [ 1.26451574e-03,  1.00000000e+00,  0.00000000e+00, ...,
        -6.00082818e-03, -6.00909967e-02,  2.49992083e-02],
       [ 5.52577176e-04,  0.00000000e+00,  1.00000000e+00, ...,
        -1.30006374e-02,  0.00000000e+00,  1.95499646e-02],
       ...,
       [ 7.52238457e-02, -6.00082818e-03, -1.30006374e-02, ...,
         1.00000000e+00,  5.07144903e-02,  5.44538770e-02],
       [-2.57125541e-02, -6.00909967e-02,  0.00000000e+00, ...,
         5.07144903e-02,  1.00000000e+00, -1.24714266e-02],
       [ 1.09323166e-02,  2.49992083e-02,  1.95499646e-02, ...,
         5.44538770e-02, -1.24714266e-02,  1.00000000e+00]])

In [9]:
# 고려할 이웃의 수
k = 5

# 각 유저별로 가장 거리가 짧았던 5명이 있는 위치
nearest_neighbors=np.argsort(distance_matrix,axis=1)[:,1:k+1]  # 정렬된 인덱스 값을 확인 , 자기 자신 제외 조회
nearest_neighbors

array([[500, 369,  70, 394, 556],
       [510,  53, 549, 211, 169],
       [313, 182,  59,  83, 172],
       ...,
       [425, 516, 415, 597,   9],
       [207, 172,  48, 209, 394],
       [147, 550, 172,  46,  42]])

개선해야할 코드

In [23]:
print(df.index)


Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       601, 602, 603, 604, 605, 606, 607, 608, 609, 610],
      dtype='int64', name='userId', length=610)


In [11]:
# 0 번째 사람의 영화를 추천할 예정
user = 0
user_ratings=df[user]
user_nan_mask = nan_mask[user]

# 유저가 평가하지 않은 영화의 위치
unrated_indices=np.where(user_nan_mask)[0]

# 영화별 예측된 평점들을 저장해놓을 장소
predictions = {}

neibors_indices = nearest_neighbors[user] # 이웃유저들의 평점 확인
#print(neibors_indices)


# 평가하지 않은 영화에 대해 이웃의 평점 가져오기
for movie_idx in unrated_indices:
    neigbor_ratings = [] # 이웃들이 이 영화를 몇점으로 평가했는가
    for neigbor_idx in neibors_indices:
        if not (nan_mask[neigbor_idx][movie_idx]):  # 영화를 봤는지 안봤는지
            neigbor_ratings.append(df[neigbor_idx][movie_idx])
    if neigbor_ratings !=[]:
        predictions[movie_idx] = np.mean(neigbor_ratings)

predictions

{1: 3.0,
 4: 3.0,
 6: 3.5,
 7: 3.0,
 9: 3.8333333333333335,
 10: 3.0,
 14: 1.0,
 15: 3.0,
 16: 2.0,
 17: 5.0,
 19: 1.0,
 20: 3.0,
 23: 2.0,
 24: 2.0,
 26: 3.0,
 31: 3.0,
 32: 3.0,
 33: 3.0,
 35: 3.5,
 41: 3.0,
 44: 2.0,
 53: 3.0,
 54: 3.0,
 55: 3.5,
 65: 2.0,
 77: 4.0,
 82: 3.0,
 84: 3.6666666666666665,
 91: 3.0,
 99: 3.25,
 109: 2.0,
 113: 2.0,
 116: 5.0,
 123: 4.5,
 131: 3.0,
 133: 3.5,
 138: 4.333333333333333,
 140: 3.0,
 144: 4.0,
 145: 4.0,
 153: 1.0,
 176: 3.5,
 217: 3.5,
 220: 3.0,
 254: 3.5,
 276: 3.0,
 277: 4.0,
 287: 3.0,
 297: 4.0,
 302: 4.0,
 311: 1.5,
 313: 3.0,
 322: 3.0,
 326: 4.0,
 332: 3.0,
 334: 3.0,
 337: 3.5,
 355: 3.0,
 364: 3.0,
 365: 3.0,
 383: 3.0,
 396: 1.0,
 404: 3.0,
 421: 1.0,
 422: 2.0,
 431: 3.5,
 438: 3.0,
 454: 4.0,
 455: 4.0,
 474: 3.5,
 504: 3.0,
 506: 2.0,
 507: 3.3333333333333335,
 512: 3.0,
 514: 4.0,
 521: 3.0,
 522: 4.0,
 527: 3.0,
 533: 3.0,
 540: 3.0,
 545: 4.0,
 552: 3.0,
 576: 2.5,
 578: 3.0,
 607: 4.0,
 613: 4.5,
 622: 4.0,
 629: 4.0,
 630: 5

In [12]:
movies = pd.read_csv('/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/movies.csv')

movie_names = {}
for i in range(len(movies)):
    a = movies.iloc[i]
    movie_names[a['movieId']] = a['title']
movie_names

{1: 'Toy Story (1995)',
 2: 'Jumanji (1995)',
 3: 'Grumpier Old Men (1995)',
 4: 'Waiting to Exhale (1995)',
 5: 'Father of the Bride Part II (1995)',
 6: 'Heat (1995)',
 7: 'Sabrina (1995)',
 8: 'Tom and Huck (1995)',
 9: 'Sudden Death (1995)',
 10: 'GoldenEye (1995)',
 11: 'American President, The (1995)',
 12: 'Dracula: Dead and Loving It (1995)',
 13: 'Balto (1995)',
 14: 'Nixon (1995)',
 15: 'Cutthroat Island (1995)',
 16: 'Casino (1995)',
 17: 'Sense and Sensibility (1995)',
 18: 'Four Rooms (1995)',
 19: 'Ace Ventura: When Nature Calls (1995)',
 20: 'Money Train (1995)',
 21: 'Get Shorty (1995)',
 22: 'Copycat (1995)',
 23: 'Assassins (1995)',
 24: 'Powder (1995)',
 25: 'Leaving Las Vegas (1995)',
 26: 'Othello (1995)',
 27: 'Now and Then (1995)',
 28: 'Persuasion (1995)',
 29: 'City of Lost Children, The (Cité des enfants perdus, La) (1995)',
 30: 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 31: 'Dangerous Minds (1995)',
 32: 'Twelve Monkeys (a.k.a. 12 Monkeys) (199

In [13]:
# 예측된 평점을 내림차순으로 정렬
sorted_predictions = sorted(predictions.items(), key=lambda x: x[1], reverse=True)
# 추천할 영화의 수
top_N = 5
recommendations = sorted_predictions[:top_N]
df = ratings.pivot_table(index = "userId", columns = "movieId", values = "rating", aggfunc="sum")
for i in recommendations:
    movie_id = df.iloc[:, i[0]].name
    name = movie_names[movie_id]
    print(f"추천영화 : {name} (예측평점 {i[1]}점)")

추천영화 : Four Rooms (1995) (예측평점 5.0점)
추천영화 : Birdcage, The (1996) (예측평점 5.0점)
추천영화 : Phenomenon (1996) (예측평점 5.0점)
추천영화 : Top Gun (1986) (예측평점 5.0점)
추천영화 : Star Trek: First Contact (1996) (예측평점 5.0점)


In [27]:
print(630 in movie_names)


False


#### 코사인 유사도, 유클리드 거리 차이

- 코사인 유사도 : 두 벡터 간의 각도를 계산하여 유사성을 측정 , 두 유저가 영화를 동일한 비율로 좋아하더라도, 그 평점의 절대적 크기는 무시 -> 평점 패턴(방향성)에만 초점이 맞춰짐

    - 예시 : 한 유저가 5점, 다른 유저가 4점을 주었더라도 둘의 평점 패턴이 유사하면 코사인 유사도는 높게 나옴

    - 장점 : 다른 유저들과의 영화 평점의 유사한 패턴을 찾기 좋다 , 절대적인 평점이 다르더라도 영화 취향이 비슷하다면 추천에 유리


- 유클리드 거리 : 두 유저 간의 평점 차이를 기반으로 유사성을 측정. 평점간 차이를 직접적으로 계산하기에 절대적 평점 크기가 중요  -> 유사한 점수를 줬다면 유사도가 높고, 큰차이가 나면 유사도가 낮음

    - 장점 : 평점의 절대적인 차이를 고려하기에 , 유저 간에 실제로 얼마나 다른 점수를 줬는지 정확하게 반영함

#### 결과가 다른 이유

- 코사인 유사도 : 평점 패턴이 비슷한 유저에게 높은 유사도를 줌 -> 절대적 평점 차이 무시 , 즉, 평점 크기가 달라도 유사한 영화 선호 경향이 있으면 추천할 가능성 높음

- 유클리드 거리 : 평점 차이를 직접적으로 고려하기에 , 비슷한 점수를 준 유저들을 기반으로 추천 , 즉, 절대적인 평점 차이가 큰 경우에 유사도가 낮게 평가됨

#### 두 방식 차이 분석

- 코사인 유사도 방식의 추천: 다양한 평점 패턴을 반영하여 사용자가 보지 않은 영화들에 대해 유사한 취향을 가진 사람들이 추천한 영화를 제공.

- 유클리드 거리 방식의 추천: 절대적인 점수 차이를 반영하여, 실제로 사용자가 비슷한 점수를 줄 만한 영화를 추천.

#### 개선사항

-코사인 유사도, 유클리드 거리의 각각의 장점을 활용하여 두 결과를 결합한 모델


- 코사인 유사도 : 평점 패턴 잘 반영 but 절대적 차이 무시
- 유클리드 거리 : 절대적 평점 차이 잘 고려

결론


코사인 유사도는 취향의 패턴을 반영하므로, 사용자의 평점 성향을 반영한 영화를 더 잘 추천


유클리드 거리는 절대적인 평점을 더 많이 고려하므로, 사용자가 실제로 높은 점수를 줄 가능성이 높은 영화를 추천



#### 개선 코드

In [1]:
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances, cosine_similarity

# 1. 유클리드 거리 계산
def calc_euclidean_distances(ratings):
    filled_ratings = ratings.copy()  # 원본 데이터 복사
    for i in range(len(filled_ratings)):
        mean = np.nanmean(filled_ratings[i])  # 각 행의 평균 계산
        filled_ratings[i] = np.nan_to_num(filled_ratings[i], nan=mean)  # NaN을 평균으로 대체
        filled_ratings[i] -= mean  # 평균 빼기
    return euclidean_distances(filled_ratings)

# 2. 코사인 유사도 계산
def calc_cosine_similarity(ratings):
    filled_ratings = ratings.copy()  # 원본 데이터 복사
    for i in range(len(filled_ratings)):
        mean = np.nanmean(filled_ratings[i])  # 각 행의 평균 계산
        filled_ratings[i] = np.nan_to_num(filled_ratings[i], nan=mean)  # NaN을 평균으로 대체
        filled_ratings[i] -= mean  # 평균 빼기
    return cosine_similarity(filled_ratings)


In [2]:
# 3. 유사도 결합
def combine_similarity(euclidean_distances, cosine_similarity):
    euclidean_similarity = 1 / (1 + euclidean_distances)
    combined_similarity = (euclidean_similarity + cosine_similarity) / 2
    return combined_similarity


In [3]:
# 4. 사용자별 추천
def recommend_movies(ratings, user, k=2, top_n=5):
    euclidean_dists = calc_euclidean_distances(ratings)
    cosine_sims = calc_cosine_similarity(ratings)
    combined_sims = combine_similarity(euclidean_dists, cosine_sims)

    # 유사한 이웃 찾기
    neighbors = np.argsort(-combined_sims[user])[1:k+1]
    user_ratings = ratings[user]
    unrated_movies = np.where(np.isnan(user_ratings))[0]

    predictions = {}

    for movie in unrated_movies:
        neighbor_ratings = ratings[neighbors, movie]
        valid_ratings = neighbor_ratings[~np.isnan(neighbor_ratings)]
        if len(valid_ratings) > 0:
            predictions[movie] = np.mean(valid_ratings)
        else:
            predictions[movie] = np.nan

    sorted_predictions = sorted(predictions.items(), key=lambda x: x[1], reverse=True)
    return sorted_predictions[:top_n]

In [4]:
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances, cosine_similarity
import pandas as pd

# 평점 데이터 로드
ratings = pd.read_csv('/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/ratings.csv')

# 영화 데이터 로드
movies = pd.read_csv('/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/movies.csv')

# 영화 ID와 제목의 매핑 생성
movie_names = {}
for i in range(len(movies)):
    a = movies.iloc[i]
    movie_names[a['movieId']] = a['title']








In [ ]:

# 추천 실행 (예시로 0번 사용자를 위한 추천)
user = 0
top_n = 5  # 상위 5개 추천
recommendations = recommend_movies(ratings.values, user, top_n=top_n)

In [ ]:
# 추천 영화 출력
for i in recommendations:
    movie_id = i[0]
    predicted_rating = i[1]
    if movie_id in movie_names:  # 영화가 movie_names에 있는지 확인
        print(f'추천 영화: {movie_names[movie_id]} (예측 평점: {predicted_rating:.2f}점)')
    else:
        print(f"영화 ID {movie_id}는 movie_names에 없습니다.")
