## 행렬 인수분해

In [1]:
import numpy as np


# 원본 평점 데이터
A = np.array([[4,1,5,4,1],
              [2,3,5,2,3],
              [1,3,4,1,3],
              [2,2,4,2,2],
              [1,3,4,1,3]])
A

array([[4, 1, 5, 4, 1],
       [2, 3, 5, 2, 3],
       [1, 3, 4, 1, 3],
       [2, 2, 4, 2, 2],
       [1, 3, 4, 1, 3]])

In [5]:
array1 = np.array([[4,1],
                  [2,3],
                   [1,3],
                  [2,2],
                  [1,3]])

array2 = np.array([[1,0,1,1,0],
                  [0,1,1,0,1]])

In [6]:
array1.shape , array2.shape

((5, 2), (2, 5))

In [7]:
array1 @ array2

array([[4, 1, 5, 4, 1],
       [2, 3, 5, 2, 3],
       [1, 3, 4, 1, 3],
       [2, 2, 4, 2, 2],
       [1, 3, 4, 1, 3]])

In [8]:
A = np.array([[4,1,5,np.nan,1],
              [2,3,np.nan,2,3],
              [1,np.nan,4,1,3],
              [np.nan,2,4,np.nan,2],
              [1,np.nan,4,1,3]])
A

array([[ 4.,  1.,  5., nan,  1.],
       [ 2.,  3., nan,  2.,  3.],
       [ 1., nan,  4.,  1.,  3.],
       [nan,  2.,  4., nan,  2.],
       [ 1., nan,  4.,  1.,  3.]])

In [10]:
mask = ~np.isnan(A)
mask

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True,  True,  True]])

In [38]:
A.shape

(5, 5)

In [18]:
import random

k = 2

m,n = A.shape

U =  np.random.rand(m , k)
V  = np.random.rand(n , k)



In [27]:
lr = 0.01

for i in range(5000):

    A_pred = U @ V.T
    # print(A_pred)

    E = np.zeros((m,n)) # 0 행렬 생성
    # print(E)
    E[mask] = A_pred[mask]- A[mask] # 오차 마스크

    U_grad = E @ V
    V_grad = E.T @ U

    U -=  U_grad * lr
    V -=  V_grad * lr

    loss = (np.sum(E[mask] **2))
    # print(loss)


1.933972949478306e-08
1.9277443499572227e-08
1.9215358134536925e-08
1.9153472753262173e-08
1.909178671149628e-08
1.9030299366989437e-08
1.8969010079458214e-08
1.8907918210943695e-08
1.8847023125362885e-08
1.8786324188700664e-08
1.8725820768952385e-08
1.8665512236301992e-08
1.860539796271171e-08
1.8545477322405808e-08
1.8485749691650315e-08
1.8426214448374817e-08
1.8366870972882608e-08
1.830771864729183e-08
1.8248756855807185e-08
1.818998498459385e-08
1.8131402421618476e-08
1.8073008557140863e-08
1.801480278315807e-08
1.7956784493615634e-08
1.789895308455143e-08
1.7841307953862638e-08
1.7783848501380358e-08
1.7726574128980116e-08
1.766948424030988e-08
1.761257824095648e-08
1.7555855538568832e-08
1.749931554259235e-08
1.744295766439668e-08
1.738678131719014e-08
1.7330785916144836e-08
1.7274970878373432e-08
1.7219335622747313e-08
1.7163879570006787e-08
1.710860214289005e-08
1.7053502765872558e-08
1.699858086528182e-08
1.6943835869439526e-08
1.688926720835589e-08
1.683487431387851e-08
1.67

In [37]:
A

array([[ 4.,  1.,  5., nan,  1.],
       [ 2.,  3., nan,  2.,  3.],
       [ 1., nan,  4.,  1.,  3.],
       [nan,  2.,  4., nan,  2.],
       [ 1., nan,  4.,  1.,  3.]])

In [36]:
A_pred

array([[3.99999999, 1.        , 5.        , 3.99999973, 1.        ],
       [2.00000003, 3.        , 5.00000004, 1.99999998, 3.        ],
       [0.99999999, 3.        , 4.        , 1.00000001, 3.        ],
       [1.99999999, 2.        , 4.        , 1.9999999 , 2.        ],
       [0.99999999, 3.        , 4.        , 1.00000001, 3.        ]])

In [35]:
A_filled = A.copy()

A_filled[~mask] = A_pred[~mask]
A_filled

array([[4.        , 1.        , 5.        , 3.99999973, 1.        ],
       [2.        , 3.        , 5.00000004, 2.        , 3.        ],
       [1.        , 3.        , 4.        , 1.        , 3.        ],
       [1.99999999, 2.        , 4.        , 1.9999999 , 2.        ],
       [1.        , 3.        , 4.        , 1.        , 3.        ]])

In [32]:
zeros = np.zeros(A_pred.shape)
zeros[~mask] += A_pred[~mask]
zeros

array([[0.        , 0.        , 0.        , 3.99999973, 0.        ],
       [0.        , 0.        , 5.00000004, 0.        , 0.        ],
       [0.        , 3.        , 0.        , 0.        , 0.        ],
       [1.99999999, 0.        , 0.        , 1.9999999 , 0.        ],
       [0.        , 3.        , 0.        , 0.        , 0.        ]])

In [34]:
for i in range(len(zeros)):
    a = zeros[i]
    for j in range(len(a)):
        if a[j] >=4:
            print(f'{i}번째 유저, {j}번째 영화 추천!')

1번째 유저, 2번째 영화 추천!


## ratings 데이터로 행렬 인수분해를 통해서 누락값들을 예측하고 영화 추천!

In [81]:
import pandas as pd

ratings = pd.read_csv('/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/ratings.csv')
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [82]:
ratings.shape

(100836, 4)

In [83]:
# 피벗 테이블 생성
ratings_pivot = ratings.pivot(index='userId', columns='movieId', values='rating')

ratings_pivot

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     NaN     NaN     NaN     NaN     NaN     2.5     NaN   
607         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
608         2.5     2.0     2.0     NaN     NaN     NaN     NaN     NaN   
609         3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
610         5.0     NaN     NaN     NaN     NaN     5.0     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
607         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
608         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
609         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
610         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
606         NaN     NaN     NaN     NaN  
607         NaN     NaN     NaN     NaN  
608         NaN     NaN     NaN     NaN  
609         NaN     NaN     NaN     NaN  
610         NaN     NaN     NaN     NaN  

[610 rows x 9724 columns]

In [84]:
# NaN 값을 마스킹
mask = ~np.isnan(ratings_pivot)

In [70]:
ratings.shape

(610, 9724)

In [85]:
import random

# 행렬 인수분해를 위한 초기화
k = 5  # 잠재 요인의 수
m, n = ratings_pivot.shape
U = np.random.rand(m, k)  # 사용자 잠재 행렬
V = np.random.rand(n, k)  # 영화 잠재 행렬


In [86]:
U.shape , V.shape

((610, 5), (9724, 5))

In [95]:
import numpy as np

# 하이퍼파라미터
m, n, k = 1000, 500, 10  # 예시로 사용자 수, 항목 수, 잠재 요인 수 설정
lr = 0.0001  # 학습률 조정
lambda_reg = 0.1  # 정규화 하이퍼파라미터

# 초기 행렬 생성 (더 작은 값으로 초기화)
U = np.random.rand(m, k) * 0.001  # 사용자 잠재 요인 행렬
V = np.random.rand(n, k) * 0.001  # 항목 잠재 요인 행렬

# 가상의 평점 행렬 생성 (예시로 0~5 사이의 값)
ratings_pivot = np.random.randint(0, 6, size=(m, n)).astype(float)

# 마스크 생성 (결측값을 처리하기 위한 마스크)
mask = np.random.rand(m, n) > 0.5  # 50%의 결측값 생성
ratings_pivot[~mask] = np.nan  # 마스크에 따라 NaN 값 할당

# 행렬 인수분해
for i in range(5000):
    # 예측 평점 계산
    ratings_pred = U @ V.T

    # 오차 마스크 설정
    E = np.zeros((m, n))
    E[mask] = ratings_pred[mask] - ratings_pivot[mask]

    # 경량 조정
    U_grad = E @ V
    V_grad = E.T @ U

    U -= U_grad * lr
    V -= V_grad * lr

    # 값 제한
    U = np.clip(U, -1, 1)  # U 값 제한
    V = np.clip(V, -1, 1)  # V 값 제한

    # 손실 계산 (정규화 추가)
    loss = np.sum(E[mask] ** 2) + lambda_reg * (np.sum(U**2) + np.sum(V**2))

    # 손실 출력 (필요 시)
    if i % 500 == 0:  # 500 에폭마다 손실 출력
        print(f"Epoch {i}, Loss: {loss:.4f}")


Epoch 0, Loss: 2284460.8865
Epoch 500, Loss: 723610.5374
Epoch 1000, Loss: 723139.4623
Epoch 1500, Loss: 680112.7506
Epoch 2000, Loss: 662932.0615
Epoch 2500, Loss: 660993.2347
Epoch 3000, Loss: 659931.0260
Epoch 3500, Loss: 659240.7062
Epoch 4000, Loss: 658753.1608
Epoch 4500, Loss: 658386.9053


In [93]:
# 예측된 평점
ratings_pred = U @ V.T

# 결측값을 예측한 평점으로 채우기
ratings_filled = ratings_pivot.copy()  # ratings_pivot이 NumPy 배열이라면
ratings_filled[~mask] = ratings_pred[~mask]


In [94]:
# 추천 시스템
for user in range(ratings_filled.shape[0]):  # 사용자 수 만큼 반복
    user_ratings = ratings_filled[user]  # 특정 사용자의 평점 배열
    recommended_movies = np.where(user_ratings >= 4)[0].tolist()  # 평점이 4 이상인 영화의 인덱스

    if recommended_movies:
        print(f'{user + 1}번째 유저, 추천할 영화 IDs: {recommended_movies}')
    else:
        print(f'{user + 1}번째 유저에게 추천할 영화가 없습니다.')


1번째 유저, 추천할 영화 IDs: [0, 5, 10, 29, 31, 34, 36, 42, 44, 45, 49, 66, 70, 71, 73, 101, 107, 108, 115, 116, 118, 120, 127, 136, 140, 141, 147, 164, 177, 182, 199, 201, 206, 215, 246, 249, 254, 256, 261, 268, 275, 279, 292, 295, 319, 322, 327, 330, 340, 349, 355, 357, 363, 366, 367, 375, 380, 381, 383, 384, 394, 395, 399, 403, 415, 418, 422, 426, 432, 437, 438, 441, 449, 451, 455, 459, 466, 467, 469, 478, 481, 494, 496]
2번째 유저, 추천할 영화 IDs: [7, 8, 9, 10, 13, 14, 24, 25, 38, 43, 52, 59, 63, 67, 68, 79, 84, 96, 97, 99, 105, 113, 115, 116, 126, 138, 141, 143, 158, 161, 163, 166, 168, 174, 178, 186, 187, 197, 202, 203, 220, 223, 226, 227, 229, 236, 239, 241, 253, 257, 270, 271, 276, 279, 286, 313, 314, 315, 318, 326, 330, 333, 350, 352, 355, 361, 377, 381, 388, 397, 406, 407, 411, 417, 422, 427, 430, 447, 449, 452, 464, 466, 467, 469, 475, 477, 486, 488, 492, 498]
3번째 유저, 추천할 영화 IDs: [15, 18, 25, 29, 44, 45, 46, 48, 49, 58, 59, 69, 83, 84, 94, 99, 114, 115, 120, 123, 126, 127, 147, 154, 155, 176

### 풀이

In [116]:
import numpy as np

# 하이퍼파라미터
m, n, k = 1000, 500, 10  # 예시로 사용자 수, 항목 수, 잠재 요인 수 설정
lr = 0.0001  # 학습률 조정
lambda_reg = 0.1  # 정규화 하이퍼파라미터

# 초기 행렬 생성 (더 작은 값으로 초기화)
U = np.random.rand(m, k) * 0.001  # 사용자 잠재 요인 행렬
V = np.random.rand(n, k) * 0.001  # 항목 잠재 요인 행렬

# 가상의 평점 행렬 생성 (예시로 0~5 사이의 값)
ratings_pivot = np.random.randint(0, 6, size=(m, n)).astype(float)

# 마스크 생성 (결측값을 처리하기 위한 마스크)
mask = np.random.rand(m, n) > 0.5  # 50%의 결측값 생성
ratings_pivot[~mask] = np.nan  # 마스크에 따라 NaN 값 할당

# 행렬 인수분해
for i in range(5000):
    # 예측 평점 계산
    ratings_pred = U @ V.T

    # 오차 마스크 설정
    E = np.zeros((m, n))
    E[mask] = ratings_pred[mask] - ratings_pivot[mask]

    # 경량 조정
    U_grad = E @ V
    V_grad = E.T @ U

    U -= U_grad * lr
    V -= V_grad * lr

    # 값 제한
    U = np.clip(U, -1, 1)  # U 값 제한
    V = np.clip(V, -1, 1)  # V 값 제한

    # 손실 계산 (정규화 추가)
    loss = np.sum(E[mask] ** 2) + lambda_reg * (np.sum(U**2) + np.sum(V**2))

    # 손실 출력 (필요 시)
    if i % 500 == 0:  # 500 에폭마다 손실 출력
        print(f"Epoch {i}, Loss: {loss:.4f}")


Epoch 0, Loss: 2288034.8776
Epoch 500, Loss: 724867.8299
Epoch 1000, Loss: 724372.3983
Epoch 1500, Loss: 680639.8166
Epoch 2000, Loss: 663833.7954
Epoch 2500, Loss: 661766.7417
Epoch 3000, Loss: 660670.0412
Epoch 3500, Loss: 659983.2183
Epoch 4000, Loss: 659514.3437
Epoch 4500, Loss: 659174.1322


In [119]:
df_filled = df.copy()
df_filled

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     NaN     NaN     NaN     NaN     NaN     2.5     NaN   
607         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
608         2.5     2.0     2.0     NaN     NaN     NaN     NaN     NaN   
609         3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
610         5.0     NaN     NaN     NaN     NaN     5.0     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
607         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
608         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
609         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
610         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
606         NaN     NaN     NaN     NaN  
607         NaN     NaN     NaN     NaN  
608         NaN     NaN     NaN     NaN  
609         NaN     NaN     NaN     NaN  
610         NaN     NaN     NaN     NaN  

[610 rows x 9724 columns]

In [120]:
df_filled[~mask] = df_pred[~mask]
df_filled

IndexError: boolean index did not match indexed array along dimension 0; dimension is 610 but corresponding boolean dimension is 1000

In [121]:
zeros = np.zeros(df_pred.shape)
zeros[~mask] += df_pred[~mask]
zeros

IndexError: boolean index did not match indexed array along dimension 0; dimension is 610 but corresponding boolean dimension is 1000

In [122]:
movies = pd.read_csv("/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/movies.csv")
movie_names = {}
for i in range(len(movies)):
    a = movies.iloc[i]
    movie_names[a['movieId']] = a['title']
movie_names

{1: 'Toy Story (1995)',
 2: 'Jumanji (1995)',
 3: 'Grumpier Old Men (1995)',
 4: 'Waiting to Exhale (1995)',
 5: 'Father of the Bride Part II (1995)',
 6: 'Heat (1995)',
 7: 'Sabrina (1995)',
 8: 'Tom and Huck (1995)',
 9: 'Sudden Death (1995)',
 10: 'GoldenEye (1995)',
 11: 'American President, The (1995)',
 12: 'Dracula: Dead and Loving It (1995)',
 13: 'Balto (1995)',
 14: 'Nixon (1995)',
 15: 'Cutthroat Island (1995)',
 16: 'Casino (1995)',
 17: 'Sense and Sensibility (1995)',
 18: 'Four Rooms (1995)',
 19: 'Ace Ventura: When Nature Calls (1995)',
 20: 'Money Train (1995)',
 21: 'Get Shorty (1995)',
 22: 'Copycat (1995)',
 23: 'Assassins (1995)',
 24: 'Powder (1995)',
 25: 'Leaving Las Vegas (1995)',
 26: 'Othello (1995)',
 27: 'Now and Then (1995)',
 28: 'Persuasion (1995)',
 29: 'City of Lost Children, The (Cité des enfants perdus, La) (1995)',
 30: 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 31: 'Dangerous Minds (1995)',
 32: 'Twelve Monkeys (a.k.a. 12 Monkeys) (199

In [123]:
import pandas as pd

ratings = pd.read_csv('/content/drive/MyDrive/IMbank_추천시스템/추천시스템 실습 데이터/data/ratings.csv')

df = ratings.pivot(index='userId', columns='movieId', values='rating')
columns = df.columns

user = 0

a = zeros[user]
a

array([0., 0., 0., ..., 0., 0., 0.])

In [124]:
for i in range(len(a)):
    if a[i] >=4.8:
        idx = columns[i]
        name = movie_names[idx]
        print(f'{name} 추천!')